apiVersion: v1
kind: Service
metadata:
  name: rqlite-svc-internal
  namespace: spire
spec:
  clusterIP: None
  publishNotReadyAddresses: True
  selector:
    db: rqlite
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: rqlite-svc
  namespace: spire
spec:
  selector:
    db: rqlite
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-server
  namespace: spire
  labels:
    app: spire-server
spec:
  replicas: 3
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: spire-server
      db: rqlite # has to match .spec.template.metadata.labels
  serviceName: rqlite-svc-internal
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-server
        db: rqlite # has to match .spec.selector.matchLabels
    spec:
      serviceAccountName: spire-server
      terminationGracePeriodSeconds: 10
      containers:
        - name: spire-server
          image: ghcr.io/spiffe/spire-server:1.5.1
          args:
            - -config
            - /run/spire/config/server.conf
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-data
              mountPath: /run/spire/data
              readOnly: false
            - name: rqlite-file
              mountPath: /rqlite/file
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: rqlite
          image: rqlite/rqlite:8.22.1
          args:
          - -disco-mode=dns
          - -disco-config={"name":"rqlite-svc-internal"}
          - -bootstrap-expect=3
          - -join-interval=3s
          - -join-attempts=3000
          - -raft-cluster-remove-shutdown=true
          ports:
          - containerPort: 4001
            name: rqlite
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /readyz
              port: 4001
            periodSeconds: 5
            timeoutSeconds: 2
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /readyz?noleader
              port: rqlite
            initialDelaySeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          volumeMounts:
          - name: rqlite-file
            mountPath: /rqlite/file
      volumes:
        - name: spire-config
          configMap:
            name: spire-server
        - name: spire-data
          emptyDir:
            medium: Memory
        - name: rqlite-file
          emptyDir:
            medium: Memory
